# Run the project's linting suite via Pre-Commit
name: Lint

on:  # yamllint disable-line rule:truthy
  push:
    branches: [master, '*.*']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master, '*.*']

jobs:
  lint:
    name: Lint Python ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          python-version: '3.9'
        - os: ubuntu-latest
          python-version: '3.7'
        - os: windows-latest
          python-version: '3.8'
        - os: macos-latest
          python-version: '3.8'
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create virtualenv
      uses: syphar/restore-virtualenv@v1
      id: env
    - name: Print basic Python info
      shell: python
      run: |
        import sys
        print(sys.executable, sys.version, sep='\n')
    - name: Install baseline deps
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install development dependencies
      run: pip install --upgrade -r requirements-dev.txt
    - name: Install package
      run: pip install --upgrade .
    - name: Pip check
      run: pip check
    - name: Run main Pre-Commit hooks
      uses: pre-commit/action@v2.0.3
